In [1]:
#1 50-100 хүртэл тоон утга бүхий нэг хэмжээст массив (вектор) үүсгэ. 
import numpy as np
A = np.arange(50,100)
A

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [2]:
#2 Арван ширхэг 1, арван ширхэг 0, арван ширхэг 6 тоо бүхий нэг хэмжээст массивууд (вектор) үүсгэ.
import numpy as np
a=np.ones(10)
b=np.zeros(10)
c=np.ones(10)*6
np.concatenate([a,b,c])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [3]:
#3 20-32 хүртэл тоон утга бүхий 3x4 хэмжээтэй массив үүсгэ.
import numpy as np
a=np.arange(20,32).reshape((3,4))
a


array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [4]:
#4 Диагональ нь 1-ийн тоо, бусад нь 0 байх 3x3 хэмжээтэй массив үүсгэ.
import numpy as np
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
#5 Диагональ нь 1-5 хүртэл тоо, бусад нь 0 байх 5х5 хэмжээтэй массив үүсгэ.
import numpy as np
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [6]:
#6 Хоёр хэмжээстэй массив үүсгэж, нийт элементүүдийн нйилөэр, багана, мөрийн нийлбэрүүдийг хэвлэ.
import numpy as np
y=np.random.randn(5,2)
print(y)
a=np.sum(y)
b=np.sum(y, axis=0)
c=np.sum(y, axis=1)
print(a,b,c)

[[-0.50451929  0.00573611]
 [ 1.16468271 -0.74616231]
 [-0.66612787 -0.43110033]
 [ 0.42314563  1.33568275]
 [ 0.53031978 -1.40027732]]
-0.2886201392126806 [ 0.94750095 -1.23612109] [-0.49878318  0.4185204  -1.09722819  1.75882838 -0.86995754]


In [12]:
#7 Спортын сайтуудын мэдээллийг ашиглан хөл бөмбөгийн спортын дурын 10 тоглогчийн сүүлийн арван жилийн цалин, нийт тоглолт, оруулсан гоалуудын талаар мэдээллийг цуглуулж тус бүрээр массив үүсгэ. Үүсгэсэн массив тус бүрийн багана болон мөрүүдийн нийлбэрийг хэвлэ.
import numpy as np
Haaland = np.random.randn(5,5)
Saka = np.random.randn(5,5)
Jesus = np.random.randn(5,5)
Martinelli = np.random.randn(5,5)
Trossard = np.random.randn(5,5)
Xhaka = np.random.randn(5,5)
Martin = np.random.randn(5,5)
Jojo = np.random.randn(5,5)
Saliba = np.random.randn(5,5)
Gabriel = np.random.randn(5,5)
a=(Haaland,Saka,Jesus,Martinelli,Trossard,Xhaka,Martin,Jojo,Saliba,Gabriel)
for i in a:
    print("Баганы дагуу", np.sum(i, axis=0))
    print("Мөрийн дагуу", np.sum(i, axis=1))

Баганы дагуу [-0.93200436 -2.90959875 -0.94454792 -3.71371145  3.01986957]
Мөрийн дагуу [-3.22113817 -0.53233698 -2.45983067  3.38546103 -2.65214812]
Баганы дагуу [ 2.68905114 -5.46369991 -3.23851943 -0.65912156  0.81973935]
Мөрийн дагуу [-2.2835021  -1.3329578  -0.01037958 -1.16955335 -1.05615759]
Баганы дагуу [-3.11550046 -0.59379329  3.00908635  2.1837971   3.73642728]
Мөрийн дагуу [ 3.13162042 -0.97446845  1.05054476  0.43019085  1.58212939]
Баганы дагуу [-0.43891773 -2.19728701 -0.83817537  0.74089716 -0.4018022 ]
Мөрийн дагуу [-3.8227095  -0.35102769  0.5220447  -1.36186562  1.87827295]
Баганы дагуу [-1.54134736 -1.68121739 -0.08794676  4.87830179  5.13661319]
Мөрийн дагуу [ 3.99559794  2.85244818 -0.13220238 -2.3392688   2.32782853]
Баганы дагуу [-0.22646987  2.27545655 -4.40925051 -1.12533669  3.6842468 ]
Мөрийн дагуу [-3.25754122  2.67749246  1.26397755 -0.57559421  0.09031171]
Баганы дагуу [-2.31756775 -2.19565559  1.32910351  2.40656266  2.11050072]
Мөрийн дагуу [ 0.07866021